---
abstract: 'Generic session management engine for web applications'
author:
  - 'Gligan Calin Horea <gliganh@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Session
no_index:
  directory:
    - t
    - inc
requires:
  JSON: '0'
  Storable: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::More: '0'
version: '0.12'
